
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"  
    open-pull-requests-limit: 10
    labels:
      - "pr:e2e"
      - "type:maintenance"
      - "dependencies"
      - "pr:daveit"
      - "pr:platform"
    ignore:
      - dependency-name: "@playwright/test" #We have to source the playwright container which is not detected by Dependabot
      - dependency-name: "playwright-core" #We have to source the playwright container which is not detected by Dependabot
      - dependency-name: "@babel/eslint-parser" #Lots of noise in these type patch releases.
        update-types: ["version-update:semver-patch"] 
      - dependency-name: "eslint-plugin-vue" #Lots of noise in these type patch releases.  
        update-types: ["version-update:semver-patch"]
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"    
    labels:
      - "type:maintenance"
      - "dependencies"
      - "pr:daveit"
