version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 10
    labels:
      - 'pr:daveit'
      - 'pr:e2e'
      - 'type:maintenance'
      - 'dependencies'
      - 'pr:platform'
    ignore:
      #We have to source the playwright container which is not detected by Dependabot
      - dependency-name: '@playwright/test'
      - dependency-name: 'playwright-core'
      #Lots of noise in these type patch releases.
      - dependency-name: '@babel/eslint-parser'
        update-types: ['version-update:semver-patch']
      - dependency-name: 'eslint-plugin-vue'
        update-types: ['version-update:semver-patch']
      - dependency-name: 'babel-loader'
        update-types: ['version-update:semver-patch']
      - dependency-name: 'sinon'
        update-types: ['version-update:semver-patch']
      - dependency-name: 'moment-timezone'
        update-types: ['version-update:semver-patch']
      - dependency-name: '@types/lodash'
        update-types: ['version-update:semver-patch']
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
    labels:
      - 'pr:daveit'
      - 'type:maintenance'
      - 'dependencies'
