
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"  
    open-pull-requests-limit: 10
    labels:
      - "pr:e2e"
      - "type:maintenance"
      - "dependencies"
      - "pr:daveit"
      - "pr:platform"
    ignore:
      #Temporarily Ignore until we address https://github.com/nasa/openmct/issues/6483
      - dependency-name: "typescript"
      #We have to source the playwright container which is not detected by Dependabot
      - dependency-name: "@playwright/test"
      - dependency-name: "playwright-core"
      #Lots of noise in these type patch releases.
      - dependency-name: "@babel/eslint-parser"
        update-types: ["version-update:semver-patch"] 
      - dependency-name: "eslint-plugin-vue"
        update-types: ["version-update:semver-patch"]
      - dependency-name: "babel-loader"
        update-types: ["version-update:semver-patch"]
      - dependency-name: "sinon"
        update-types: ["version-update:semver-patch"]
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"    
    labels:
      - "type:maintenance"
      - "dependencies"
      - "pr:daveit"
